version: '3'

services:
  bot:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/python.Dockerfile
    working_dir: '/cmd/'
    tty: true
    volumes:
      - ./cmd:/cmd
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: discord
      TZ: "Asia/Tokyo"
    ports:
      - "3000:3306"
    tty: true
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=P@ssw0rd
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions

# MySQLとgolangを追加し、参加したユーザー情報を登録。